Repository Bo4kaa/work_1, pull requests merged in 2023-09, with the labels that each got.

#12 Убери лишние пробелы в style.css
  css/style.css
Labels: refactor

#18 enhancement: В html сделай название проекта на work_1
  index.html
Labels: enhancement

#20 refactor: Избавься от всех style в тегах
  index.html
Labels: refactor

#24 refactor: Переименуй normalise в normalize #9
  css/normalize.css
Labels: refactor

#25 refactor: Первые 28 из style.css строчек перенеси в normalize.css
  css/normalize.css
  css/style.css
Labels: refactor

#27 bug first refactor wontfix: В 7 строчке html поменяй путь к normalize.css
  index.html
Labels: bug

#28 refactor: Переименуй фотографии #4
  css/normalize.css
  css/style.css
  img/Frame (1).png
  img/Jacob-Paulaner.png
  img/Pocket_casts.png
  img/SpotIfy.png
  img/arrow.png
  img/column.png
  img/facebook.png
  img/info-negr.png
  img/instagram.png
  img/microphone.png
  img/podcast.png
  img/promo-negr.png
  img/soundcloud.png
  img/star.png
  img/twitter.png
  img/x-proga.png
  index.html
Labels: refactor

#29 refactor: Заголовок h1 должен быть только один, сделай заголовки других подуровней #15
  css/normalize.css
  css/style.css
  index.html
Labels: refactor

#38 Сделай звездочки svg #7 - Fix #7
  css/style.css
  img/STAR.svg
  index.html
Labels: refactor

#40 fix: фикс фона звезд
  css/style.css
  index.html
Labels: bug

#42 refactor: Сделай чтобы навигация была nav и ul li #3
  css/style.css
  index.html
Labels: refactor

#43 refactor: обертка в main #22
  index.html
Labels: refactor

#46 refactor: убрал padding #23
  css/style.css
  img/Vector.svg
  index.html
Labels: refactor

#49 refactor: сделал но фотка была уже на странцие#14
  index.html
Labels: refactor

#53 refactor: Сделал поля инпутом #52
  css/style.css
  index.html
Labels: refactor

#54 refactor: Сделать next level как на макете
  css/style.css
  img/line.svg
  index.html
  script.js
Labels: refactor
