Repository Bo4kaa/work_1, pull requests merged in 2023-10, with the labels that each got.

#57 Решил проблему с переполнением #48
  css/style.css
Labels: bug

#58 Сделал(типо сам) шапку фиксированной #55
  css/style.css
Labels: refactor

#59 refactor: Изменить формат некоторых фоток
  img/Pocket-casts.svg
  img/Pocket_casts.png
  img/SpotIfy.png
  img/column.jpg
  img/column.png
  img/facebook.png
  img/facebook.svg
  img/info-negr.jpg
  img/info-negr.png
  img/instagram.png
  img/instagram.svg
  img/microphone.jpg
  img/microphone.png
  img/podcast.png
  img/podcast.svg
  img/soundcloud.png
  img/soundcloud.svg
  img/spotify.svg
  img/star.png
  img/twitter.png
  img/twitter.svg
  img/x-proga.png
  img/x-proga.svg
  index.html
Labels: bug, refactor, first

#61 язык_md#35
  README.md
Labels: documentation

#60 refactor: Переименуй логические блоки
  .md
  css/style.css
  index.html
Labels: refactor

#64 сделал_адаптив#5
  css/font.css
  css/media.css
  css/normalize.css
  css/style.css
  index.html
Labels: enhancement

#68 enhancement: Сделай доступность на сайте
  css/media.css
  css/normalize.css
  css/style.css
  index.html
Labels: enhancement

#70 Создал перменные для цветов используя --root
  css/style.css
Labels: enhancement
